---
title: "QQ plots for SAIGE meta-analysis burden results"
author: "Austin Hammermeister Suger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      comment = "",
                      cache = FALSE)

library(pacman)

p_load(rlang, tidyverse, data.table, R.utils,
       ggplot2, ggpubr)
```

```{r custom_qq_function}
gg_qq <- function(pvector, lambda) {
  observed <- -log10(sort(pvector))
  expected <- -log10(ppoints(length(pvector)))
  
  df <- data.frame(Expected = expected, Observed = observed)
  
  ggplot(df, aes(x = Expected, y = Observed)) +
    geom_point(size = 1, alpha = 0.6) +
    geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed") +
    labs(title = paste0("λ = ", lambda),
         x = "Expected -log10(p)",
         y = "Observed -log10(p)") +
    theme_minimal() +
    theme(plot.title = element_text(size = 10))
}
```

```{r load_synonymous_results }
results = NULL
for (i in c("ectoderm",
            "mesoderm",
            "endoderm",
            "hormone",
            "smoking",
            "infectious")) {
  
  temp_results = fread(paste0("/lindstroem/austin_working/Dissertation/Meta/Aim1/cancer_groups/synonymous_meta_",i,".txt")) %>%
    mutate(group = i)
  
  results = rbind.data.frame(results,temp_results)
}

results$group <- factor(results$group, levels = c("ectoderm",
            "mesoderm",
            "endoderm",
            "hormone",
            "smoking",
            "infectious"))
```

```{r QQ_meta_syn, dpi=400, width = 20, height = 0}
qq_plots <- results %>%
  group_by(group) %>%
  group_split() %>%
  imap(~{
    chisq_vals <- qchisq(1 - .x$P, df = 1)  
    lambda_gc <- round(median(chisq_vals, na.rm = TRUE) / qchisq(0.5, 1), 3)
    gg_qq(pvector = .x$P, lambda = lambda_gc)
  })

plot = ggarrange(plotlist = qq_plots,
          ncol = 2, nrow = 3,
          labels = "AUTO")

ggsave("burden_syn_qq/Meta_QQ.jpeg", plot = plot, width = 6, height = 10, dpi = 400)
```


```{r QQ_UKB_syn, dpi=400, width = 10, height = 20}
qq_plots <- results %>%
  group_by(group) %>%
  group_split() %>%
  imap(~{
    chisq_vals <- qchisq(1 - .x$UKB_P, df = 1)  
    lambda_gc <- round(median(chisq_vals, na.rm = TRUE) / qchisq(0.5, 1), 3)
    gg_qq(pvector = .x$UKB_P, lambda = lambda_gc)
  })

plot = ggarrange(plotlist = qq_plots,
          ncol = 2, nrow = 3,
          labels = "AUTO")

ggsave("burden_syn_qq/UKB_QQ.jpeg", plot = plot, width = 6, height = 10, dpi = 400)
```

```{r QQ_AoURP_syn, dpi=400, width = 10, height = 20}
qq_plots <- results %>%
  group_by(group) %>%
  group_split() %>%
  imap(~{
    chisq_vals <- qchisq(1 - .x$AoU_P, df = 1)  
    lambda_gc <- round(median(chisq_vals, na.rm = TRUE) / qchisq(0.5, 1), 3)
    gg_qq(pvector = .x$AoU_P, lambda = lambda_gc)
  })

plot = ggarrange(plotlist = qq_plots,
          ncol = 2, nrow = 3,
          labels = "AUTO")

ggsave("burden_syn_qq/AoURP_QQ.jpeg", plot = plot, width = 6, height = 10, dpi = 400)

```

```{r load_missense_results }
results = NULL
for (i in c("ectoderm",
            "mesoderm",
            "endoderm",
            "hormone",
            "smoking",
            "infectious")) {
  
  temp_results = fread(paste0("/lindstroem/austin_working/Dissertation/Meta/Aim1/cancer_groups/missense_meta_",i,".txt")) %>%
    mutate(group = i)
  
  results = rbind.data.frame(results,temp_results)
}

results$group <- factor(results$group, levels = c("ectoderm",
            "mesoderm",
            "endoderm",
            "hormone",
            "smoking",
            "infectious"))
```

```{r QQ_meta_mis, dpi=400, width = 20, height = 0}
qq_plots <- results %>%
  group_by(group) %>%
  group_split() %>%
  imap(~{
    chisq_vals <- qchisq(1 - .x$P, df = 1)  
    lambda_gc <- round(median(chisq_vals, na.rm = TRUE) / qchisq(0.5, 1), 3)
    gg_qq(pvector = .x$P, lambda = lambda_gc)
  })

plot = ggarrange(plotlist = qq_plots,
          ncol = 2, nrow = 3,
          labels = "AUTO")

ggsave("burden_mis_qq/Meta_QQ.jpeg", plot = plot, width = 6, height = 10, dpi = 400)
```

```{r QQ_UKB_mis, dpi=400, width = 10, height = 20}
qq_plots <- results %>%
  group_by(group) %>%
  group_split() %>%
  imap(~{
    chisq_vals <- qchisq(1 - .x$UKB_P, df = 1)  
    lambda_gc <- round(median(chisq_vals, na.rm = TRUE) / qchisq(0.5, 1), 3)
    gg_qq(pvector = .x$UKB_P, lambda = lambda_gc)
  })

plot = ggarrange(plotlist = qq_plots,
          ncol = 2, nrow = 3,
          labels = "AUTO")

ggsave("burden_mis_qq/UKB_QQ.jpeg", plot = plot, width = 6, height = 10, dpi = 400)
```

```{r QQ_AoURP_mis, dpi=400, width = 10, height = 20}
qq_plots <- results %>%
  group_by(group) %>%
  group_split() %>%
  imap(~{
    chisq_vals <- qchisq(1 - .x$AoU_P, df = 1)  
    lambda_gc <- round(median(chisq_vals, na.rm = TRUE) / qchisq(0.5, 1), 3)
    gg_qq(pvector = .x$AoU_P, lambda = lambda_gc)
  })

plot = ggarrange(plotlist = qq_plots,
          ncol = 2, nrow = 3,
          labels = "AUTO")

ggsave("burden_mis_qq/AoURP_QQ.jpeg", plot = plot, width = 6, height = 10, dpi = 400)

```

```{r load_plof_results }
results = NULL
for (i in c("ectoderm",
            "mesoderm",
            "endoderm",
            "hormone",
            "smoking",
            "infectious")) {
  
  temp_results = fread(paste0("/lindstroem/austin_working/Dissertation/Meta/Aim1/cancer_groups/pLoF_meta_",i,".txt")) %>%
    mutate(group = i)
  
  results = rbind.data.frame(results,temp_results)
}

results$group <- factor(results$group, levels = c("ectoderm",
            "mesoderm",
            "endoderm",
            "hormone",
            "smoking",
            "infectious"))
```

```{r QQ_meta_plof, dpi=400, width = 20, height = 0}
qq_plots <- results %>%
  group_by(group) %>%
  group_split() %>%
  imap(~{
    chisq_vals <- qchisq(1 - .x$P, df = 1)  
    lambda_gc <- round(median(chisq_vals, na.rm = TRUE) / qchisq(0.5, 1), 3)
    gg_qq(pvector = .x$P, lambda = lambda_gc)
  })

plot = ggarrange(plotlist = qq_plots,
          ncol = 2, nrow = 3,
          labels = "AUTO")

ggsave("burden_plof_qq/Meta_QQ.jpeg", plot = plot, width = 6, height = 10, dpi = 400)
```

```{r QQ_UKB_plof, dpi=400, width = 10, height = 20}
qq_plots <- results %>%
  group_by(group) %>%
  group_split() %>%
  imap(~{
    chisq_vals <- qchisq(1 - .x$UKB_P, df = 1)  
    lambda_gc <- round(median(chisq_vals, na.rm = TRUE) / qchisq(0.5, 1), 3)
    gg_qq(pvector = .x$UKB_P, lambda = lambda_gc)
  })

plot = ggarrange(plotlist = qq_plots,
          ncol = 2, nrow = 3,
          labels = "AUTO")

ggsave("burden_plof_qq/UKB_QQ.jpeg", plot = plot, width = 6, height = 10, dpi = 400)
```

```{r QQ_AoURP_plof, dpi=400, width = 10, height = 20}
qq_plots <- results %>%
  group_by(group) %>%
  group_split() %>%
  imap(~{
    chisq_vals <- qchisq(1 - .x$AoU_P, df = 1)  
    lambda_gc <- round(median(chisq_vals, na.rm = TRUE) / qchisq(0.5, 1), 3)
    gg_qq(pvector = .x$AoU_P, lambda = lambda_gc)
  })

plot = ggarrange(plotlist = qq_plots,
          ncol = 2, nrow = 3,
          labels = "AUTO")

ggsave("burden_plof_qq/AoURP_QQ.jpeg", plot = plot, width = 6, height = 10, dpi = 400)
```